### ISSUE TITLE
运行第七章代码报错

### ISSUE THREAD

**Issue by yangyang12345** [hzy46/Deep-Learning-21-Examples#12]
跑已经生成好的模型python eval.py --model_file models/wave.ckpt-done --image_file img/test.jpg
和跑训练模型 python train.py -c conf/wave.yml
都报这个错
Traceback (most recent call last):
  File "eval.py", line 75, in <module>
    tf.app.run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "eval.py", line 45, in main
    generated = model.net(image, training=False)
  File "/Users/yushiyang/project/Deep-Learning-21-Examples-master/chapter_7/model.py", line 100, in net
    conv1 = relu(instance_norm(conv2d(image, 3, 32, 9, 1)))
  File "/Users/yushiyang/project/Deep-Learning-21-Examples-master/chapter_7/model.py", line 9, in conv2d
    x_padded = tf.pad(x, [[0, 0], [kernel / 2, kernel / 2], [kernel / 2, kernel / 2], [0, 0]], mode=mode)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1738, in pad
    tensor, paddings, mode="REFLECT", name=name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 2580, in _mirror_pad
    "MirrorPad", input=input, paddings=paddings, mode=mode, name=name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 609, in _apply_op_helper
    param_name=input_name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 60, in _SatisfiesTypeConstraint
    ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
TypeError: Value passed to parameter 'paddings' has DataType float32 not in list of allowed values: int32, int64

**Comment by hzy46** [comment]
kernel / 2 => int(kernel / 2)试试？

**Comment by yangyang12345** [comment]
@hzy46 谢谢，解决了
