### ISSUE TITLE
chapter12:Traceback (most recent call last):   File "sample.py", line 39, in <module>     tf.app.run()   File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\platform\app.py", line 126, in run     _sys.exit(main(argv))   File "sample.py", line 19, in main     FLAGS.start_string = FLAGS.start_string.decode('utf-8') AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by zhuyanshuo** [hzy46/Deep-Learning-21-Examples#5]

**Comment by hzy46** [comment]
哈喽，这一章的代码必须要用Python 2版本运行的
