### ISSUE TITLE
第三章运行train_image_classifier.py文件报错怎么办啊

### ISSUE THREAD

**Issue by sun1638650145** [hzy46/Deep-Learning-21-Examples#72]
(tensorflow) sunruiqideMacBook-Pro:tensorflow sunruiqi$ python /Users/sunruiqi/Desktop/3-Slim/slim/train_image_classifier.py \
> --train_dir = /Users/sunruiqi/Desktop/3-Slim/slim/satellite/train_dir \
> --dataset_name = satellite \
> --dataset_split_name = train \
> --dataset_dir = /Users/sunruiqi/Desktop/3-Slim/slim/satellite/data \
> --model_name = inception_v3 \
> --checkpoint_path = /Users/sunruiqi/Desktop/3-Slim/slim/satellite/pretrained/inception_v3.ckpt \
> --checkpoint_exclude_scopes = InceptionV3/Logits,InceptionV3/AuxLogits \
> --trainable_scopes = InceptionV3/Logits,InceptionV3/AuxLogits \
> --max_number_of_steps=100000 \
> --batch_size = 32 \
> --learning_rate = 0.001 \
> --learning_rate_decay_type = fixed \
> --save_interval_secs = 300 \
> --save_summaries_secs = 2 \
> --log_every_n_steps = 10 \
> --optimizer = rmsprop \
> --weight_decay= 0.00004
以上是我运行的命令
Traceback (most recent call last):
  File "/Users/sunruiqi/Desktop/3-Slim/slim/train_image_classifier.py", line 573, in <module>
    tf.app.run()
  File "/Users/sunruiqi/tensorflow/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 119, in run
    argv = flags.FLAGS(_sys.argv if argv is None else argv, known_only=True)
  File "/Users/sunruiqi/tensorflow/lib/python2.7/site-packages/tensorflow/python/platform/flags.py", line 112, in __call__
    return self.__dict__['__wrapped'].__call__(*args, **kwargs)
  File "/Users/sunruiqi/tensorflow/lib/python2.7/site-packages/absl/flags/_flagvalues.py", line 625, in __call__
    unknown_flags, unparsed_args = self._parse_args(args, known_only)
  File "/Users/sunruiqi/tensorflow/lib/python2.7/site-packages/absl/flags/_flagvalues.py", line 761, in _parse_args
    flag.parse(value)
  File "/Users/sunruiqi/tensorflow/lib/python2.7/site-packages/absl/flags/_flag.py", line 151, in parse
    self.value = self._parse(argument)
  File "/Users/sunruiqi/tensorflow/lib/python2.7/site-packages/absl/flags/_flag.py", line 169, in _parse
    'flag --%s=%s: %s' % (self.name, argument, e))
absl.flags._exceptions.IllegalFlagValueError: flag --batch_size==: invalid literal for int() with base 10: '='
这是报的错，我用的是mac os 10.14.3 Python 2.7.10 tensorflow 1.12.0,之前tfrecord文件生成有问题，现在解决了，但是运行还是有问题

**Comment by TerryLoveMl** [comment]
同求该问题

**Comment by sun1638650145** [comment]
你应该是用的tensorflow-CPU版吧，里面40、41行
tf.app.flags.DEFINE_boolean('clone_on_cpu', False,'Use CPUs to deploy clones.')
这个参数是默认使用GPU的，解决方案有两个，一个是使用GPU版，另一个是把False，改成True。
